export interface Sneaker {
  id: string;
  name: string;
  price: number;
  category: string;
  widthFit: string;
  useCaseTags: string[];
  materials: string[];
  sizes: number[];
  color: string;
  description: string;
  imageUrl: string;
}

export const mockSneakers: Sneaker[] = [
  {
    id: "snk-001",
    name: "LUMEN Aethelgard",
    price: 250,
    category: "Limited Edition",
    widthFit: "Narrow to Medium",
    useCaseTags: ["streetwear", "luxury", "statement"],
    materials: ["Italian leather", "Gold-plated accents", "Carbon fiber sole"],
    sizes: [7, 8, 9, 10, 11, 12],
    color: "Obsidian / Champagne Gold",
    description: "The flagship Aethelgard redefines nocturnal luxury. Crafted from pitch-black Italian leather with champagne gold engraved accents, designed for the bold.",
    imageUrl: "/images/snk1.jpg", 
  },
  {
    id: "snk-002",
    name: "LUMEN Velocity 'Moonrunner'",
    price: 180,
    category: "Running",
    widthFit: "Medium",
    useCaseTags: ["running", "athletic", "performance"],
    materials: ["Breathable mesh", "Vibranium-infused foam", "Silver reflective threading"],
    sizes: [6, 7, 8, 9, 10, 11, 12, 13],
    color: "Lunar Grey / Silver",
    description: "Engineered for zero-gravity feel. The Moonrunner features reflective silver threading that catches the light like a meteor in the night sky.",
    imageUrl: "/images/snk2.jpg", 
  },
  {
    id: "snk-003",
    name: "LUMEN Court Royal",
    price: 160,
    category: "Basketball",
    widthFit: "Wide-friendly",
    useCaseTags: ["basketball", "court", "supportive"],
    materials: ["Suede", "Reinforced rubber", "Metallic silver clasps"],
    sizes: [8, 9, 10, 11, 12, 13, 14],
    color: "Midnight Blue / Silver",
    description: "Dominance meets elegance. The Court Royal offers superior ankle support hidden behind a sleek, minimalist suede silhouette.",
    imageUrl: "/images/snk3.jpg",
  },
  {
    id: "snk-004",
    name: "LUMEN Drifter",
    price: 120,
    category: "Casual",
    widthFit: "Medium",
    useCaseTags: ["everyday", "casual", "walking", "comfort"],
    materials: ["Vegan leather", "Memory foam", "Matte black finish"],
    sizes: [5, 6, 7, 8, 9, 10, 11],
    color: "Vantablack",
    description: "Your everyday companion. The Drifter strips away all excess, leaving a pure, matte-black form that pairs with any outfit.",
    imageUrl: "/images/snk4.jpg",
  },
  {
    id: "snk-005",
    name: "LUMEN Zenith High",
    price: 190,
    category: "Casual",
    widthFit: "Narrow",
    useCaseTags: ["streetwear", "high-top", "fashion"],
    materials: ["Nubuck", "Brass eyelets", "Translucent sole"],
    sizes: [7, 8, 9, 10, 11, 12],
    color: "Charcoal / Gold",
    description: "A towering presence. The Zenith High combines soft nubuck with a translucent sole that glows faintly in the dark.",
    imageUrl: "/images/snk5.jpg",
  },
  {
    id: "snk-006",
    name: "LUMEN Eclipse",
    price: 290,
    category: "Limited Edition",
    widthFit: "Medium",
    useCaseTags: ["collector", "art", "luxury", "statement"],
    materials: ["Exotic leather", "Titanium heel clip", "Hand-stitched details"],
    sizes: [8, 9, 10, 11],
    color: "Void Black / Titanium",
    description: "Only 500 pairs exist. The Eclipse is an architectural marvel of footwear, featuring a titanium heel clip for structural elegance.",
    imageUrl: "/images/snk6.jpg",
  },
  {
    id: "snk-007",
    name: "LUMEN Pulse",
    price: 140,
    category: "Running",
    widthFit: "Wide-friendly",
    useCaseTags: ["running", "marathon", "breathable", "cushioned"],
    materials: ["Knit upper", "Responsive gel pod", "Recycled rubber"],
    sizes: [7, 8, 9, 10, 11, 12, 13],
    color: "Ash / Champagne",
    description: "Sustained rhythm for the long road. The Pulse features a woven knit upper that adapts to your foot, finished with a champagne gel pod.",
    imageUrl: "/images/snk7.jpg",
  },
  {
    id: "snk-008",
    name: "LUMEN Apex",
    price: 175,
    category: "Basketball",
    widthFit: "Medium",
    useCaseTags: ["basketball", "indoor", "agile"],
    materials: ["Synthetic weave", "Carbon plate", "Grip-tech rubber"],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    color: "Onyx / Silver",
    description: "Built for explosive movement. The Apex hides a carbon fiber spring plate within its stealthy, geometric silhouette.",
    imageUrl: "/images/snk8.jpg",
  },
  {
    id: "snk-009",
    name: "LUMEN Obsidian High",
    price: 210,
    category: "Casual",
    widthFit: "Medium",
    useCaseTags: ["streetwear", "high-top", "statement"],
    materials: ["Premium leather", "Matte finish", "Hidden zip"],
    sizes: [8, 9, 10, 11, 12],
    color: "Jet Black",
    description: "A towering high-top engineered from jet-black leather. Features a hidden zip and matte finish that absorbs light.",
    imageUrl: "/images/snk9.jpg",
  },
  {
    id: "snk-010",
    name: "LUMEN Velocity 'Phantom'",
    price: 150,
    category: "Running",
    widthFit: "Narrow",
    useCaseTags: ["running", "track", "lightweight"],
    materials: ["Fly-knit weave", "Carbon propulsion", "Stealth foam"],
    sizes: [7, 8, 9, 10, 11],
    color: "Phantom Grey / Gold",
    description: "Built for speed in the shadows. The Phantom features a carbon propulsion plate and a breathable weave that disappears on the foot.",
    imageUrl: "/images/snk10.jpg",
  },
  {
    id: "snk-011",
    name: "LUMEN Archon",
    price: 185,
    category: "Basketball",
    widthFit: "Wide-friendly",
    useCaseTags: ["basketball", "indoor", "performance"],
    materials: ["Textured suede", "Ankle lock system", "Gold threading"],
    sizes: [9, 10, 11, 12, 13],
    color: "Midnight Black / Gold",
    description: "Dominate the court. The Archon offers supreme ankle lock support wrapped in textured suede and intricate gold threading.",
    imageUrl: "/images/snk11.jpg",
  },
  {
    id: "snk-012",
    name: "LUMEN Solstice",
    price: 350,
    category: "Limited Edition",
    widthFit: "Medium",
    useCaseTags: ["collector", "art", "luxury"],
    materials: ["Ostrich leather", "Gold hardware", "Crystal sole"],
    sizes: [8, 9, 10],
    color: "Obsidian / Crystal",
    description: "The pinnacle of our craft. Only 100 pairs made. The Solstice features authentic ostrich leather and a semi-translucent crystal sole.",
    imageUrl: "/images/snk12.jpg",
  }
];
